name: chat_pocket_base
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  go_router: ^14.3.0
  pocketbase: ^0.18.1

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.6.8
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  riverpod_lint: ^2.6.1

flutter:
  uses-material-design: true
